name: example
description: Example app for flutter_form_builder package
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0" 

dependencies:
  modal_bottom_sheet: ^2.1.2
  open_file: ^3.3.2
  fl_chart: ^0.65.0
  pdf: ^3.10.6
  path_provider: ^2.1.1
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  flutter:
    sdk: flutter
  flutter_form_builder:
    path: ../
  form_builder_validators: ^9.0.0-dev.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sennova.png 
    - assets/coffee.png
    - assets/consulta_reporte.png
    - assets/logosenab.png
    - assets/juanzam.jpg
    - assets/linkedin.png
    - assets/github.png

